---
dependencies:
- apt-transport-https
- ca-certificates
- curl
- gnupg-agent
- software-properties-common

docker_package:
- docker-ce
- docker-ce-cli
- containerd.io

docker_compose_version: "1.24.1"
docker_compose_path: /usr/local/bin/docker-compose