---
- hosts: all
  become: true
  tasks:

    - name: 'uninstall old docker dependencies'  
      apt:
        name: ['docker', 'docker-engine', 'containerd', 'docker.io', 'runc']
        state: 'absent'
        autoremove: 'yes'
        autoclean: 'yes'


    - name: 'install docker dependencies'
      apt:
        name: '{{ item }}'
        state: 'latest'
      with_items:
        - 'apt-transport-https'
        - 'ca-certificates'
        - 'curl'
        - 'gnupg-agent'
        - 'software-properties-common'


    - name: 'add docker repo apt key'
      apt_key:
        url: 'https://download.docker.com/linux/ubuntu/gpg'
        id: '9DC858229FC7DD38854AE2D88D81803C0EBFCD88'
        state: 'present'
      register: 'add_repository_key'
      ignore_errors: true


    - name: 'add Docker repository'
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution|lower }} {{ ansible_distribution_release }} stable
        state: 'present'
        update_cache: 'yes'

    - name: 'install docker'
      apt:
        name: ['docker-ce', 'docker-ce-cli', 'containerd.io']
        state: 'latest'
        update_cache: 'yes'


    - name: 'clear apt cache'
      apt:
        autoclean: 'yes'
        autoremove: 'yes'

    - name: Check current docker-compose version.
      command: docker-compose --version
      register: docker_compose_current_version
      changed_when: false
      failed_when: false


    - name: Delete existing docker-compose version if it's different.
      file:
        path: "/usr/local/bin/docker-compose"
        state: absent
      when: >
        docker_compose_current_version.stdout is defined
        and docker_compose_version not in docker_compose_current_version.stdout


    - name: Install Docker Compose (if configured).
      get_url:
        url: https://github.com/docker/compose/releases/download/1.24.0/docker-compose-Linux-x86_64
        dest: "/usr/local/bin/docker-compose"
        mode: 0755
