---
- name: 'Uninstall Old Docker Dependencies'  
  apt:
    name: ['docker', 'docker-engine', 'containerd', 'docker.io', 'runc']
    state: 'absent'
    autoremove: 'yes'
    autoclean: 'yes'

- name: 'Install HTTPS APT Dependencies'
  apt:
    name: '{{ dependencies }}'
    state: 'latest'
    update_cache: 'yes'

- name: 'Add Docker Repo APT Key'
  apt_key:
    url: 'https://download.docker.com/linux/ubuntu/gpg'
    id: '9DC858229FC7DD38854AE2D88D81803C0EBFCD88'
    state: 'present'
  register: 'add_repository_key'
  ignore_errors: true

- name: 'Add Official Docker Repository'
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution|lower }} {{ ansible_distribution_release }} stable
    state: 'present'
    update_cache: 'yes'